import { createContext } from "react";

export const CharacterContext = createContext({
  name: "",
  race: "",
  isAttack: false,
  isHeal: false,
  isSummon: false,
  isInherited: false,
  water: "",
  fire: "",
  wind: "",
  earth: "",
  heal: "",
  detoxification: "",
  divineStrike: "",
  protection: "",
  fiends: "",
  spirits: "",
  isHowling: false,
  isTeleport: false,
  isGravityManipulation: false,
  isTimeTravel: false,
  isHypnosis: false,
  isMagicDisruption: false,
  isReincarnation: false,
  isDivination: false,
  isTemporarySoulSummoning: false,
});
